name: Publish extension to Chrome Web Store on release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Print
        run: echo ${GITHUB_REF##*/}
