name: Publish extension

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "out/DatabricksTweak_${GITHUB_REF##*/}.zip"
          asset_name: "DatabricksTweak_${GITHUB_REF##*/}.zip"
          asset_content_type: application/zip
