name: Publish extension

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Get asset name
        id: asset
        run: |
          asset=DatabricksTweak_${GITHUB_REF##*/}.zip
          echo "::set-output name=name::$asset"

      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: out/${{ steps.asset.outputs.name }}
          asset_name: ${{ steps.asset.outputs.name }}
          asset_content_type: application/zip
